# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: harmony-node
  labels:
    app: harmony
spec:
  ports:
  - name: https
    port: 443
  - name: ssh
    port: 22
  - name: http
    port: 80
  clusterIP: None
  selector:
    app: harmony
---
# Client service for connecting to any Harmony instance
apiVersion: v1
kind: Service
metadata:
  name: harmony
  labels:
    app: harmony
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 6080
  - name: ssh
    port: 22
    targetPort: 10022
  - name: http
    port: 80
    targetPort: 5080
  sessionAffinity: ClientIP
  selector:
    app: harmony
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poc-storage
  labels:
    app: harmony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harmony
spec:
  serviceName: harmony
  replicas: 1
  selector:
    matchLabels:
      app: harmony
  template:
    metadata:
      labels:
        app: harmony
    spec:
      initContainers:
      - name: init-harmony
        image: olsonjacob/harmony-container-poc:poc-0.0.2
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - "-c"
        - |
          cp -pRT /opt/harmony /opt/init-harmony
          # Skip the clone on master (ordinal index 0).
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          # Adding 1+ ordinal to match license structure
          cp "licenses/UH000$((1+$ordinal))_license_key.txt" /opt/init-harmony/license_key.txt
          cp "syncs/Sync$((1+$ordinal)).xml" /opt/init-harmony/conf/Sync.xml
        command: [/opt/init-harmony/Harmonyc, -i, /opt/harmony/0.6.zip]
        volumeMounts:
        - name: harmony
          mountPath: /opt/init-harmony
      containers:
      - name: harmony
        image: olsonjacob/harmony-container-poc:poc-0.0.2
        imagePullPolicy: IfNotPresent
        command: [ ./Harmonyc, -s, service]
        ports:
        - containerPort: 5080
          name: http
        - containerPort: 10022
          name: ssh
        - containerPort: 6080
          name: https
        volumeMounts:
        - name: harmony
          mountPath: /opt/harmony
        - name: poc-storage
          mountPath: /var/harmony/mailboxes   
      volumes:
      - name: poc-storage
        persistentVolumeClaim:
          claimName: poc-storage
  volumeClaimTemplates:
  - metadata:
      name: harmony
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
